import React, { useCallback, useState } from 'react';
import { Platform, ScrollView, StyleSheet, Text, View } from 'react-native';
import { useFocusEffect } from '@react-navigation/native';
import * as Device from 'expo-device';
import * as Notifications from 'expo-notifications';
import Constants from 'expo-constants';
import { Ionicons } from '@expo/vector-icons';
import { Badge, Card, Divider, Muted, PrimaryButton, Screen, SectionHeader, Subtitle, Title, screenContentStyle } from '../components/ui';
import { colors, spacing } from '../constants/theme';
import { getPushToken, savePushToken } from '../utils/storage';
import { withNotificationTimeout } from '../utils/notifications';

Notifications.setNotificationHandler({ handleNotification: async () => ({ shouldShowBanner: true, shouldShowList: true, shouldPlaySound: true, shouldSetBadge: false }) });
export default function PromoScreen() {
  const [permission, setPermission] = useState('unknown'); const [token, setToken] = useState<string | null>(null); const [statusNote, setStatusNote] = useState('Tap below to request permission.'); const [busy, setBusy] = useState(false);
  const refresh = useCallback(async () => { try { const perm = await withNotificationTimeout(Notifications.getPermissionsAsync()); setPermission(perm.status); setToken(await getPushToken()); } catch { setStatusNote("Notification status is temporarily unavailable."); } }, []);
  useFocusEffect(useCallback(() => { refresh(); }, [refresh]));
  async function requestAndRegister() { setBusy(true); try { if (!Device.isDevice && Platform.OS !== 'android') setStatusNote('Physical device recommended for push; local notifications still work on Android emulators.'); const current = await withNotificationTimeout(Notifications.getPermissionsAsync()); let finalStatus = current.status; if (finalStatus !== 'granted') finalStatus = (await withNotificationTimeout(Notifications.requestPermissionsAsync())).status; setPermission(finalStatus); if (finalStatus !== 'granted') { setStatusNote('Permission denied. Enable notifications in system settings to get booking alerts.'); return; } if (Platform.OS === 'android') await withNotificationTimeout(Notifications.setNotificationChannelAsync('mspace-default', { name: 'MSpace', importance: Notifications.AndroidImportance.DEFAULT })); const projectId = Constants.expoConfig?.extra?.eas?.projectId || Constants.easConfig?.projectId; try { const push = await withNotificationTimeout(Notifications.getExpoPushTokenAsync(projectId ? { projectId } : undefined)); await savePushToken(push.data); setToken(push.data); setStatusNote('Permission granted. Your Expo push token is stored locally.'); } catch (e) { const msg = e instanceof Error ? e.message : 'token unavailable'; setStatusNote(`Permission granted. Local notifications OK. Push token not available yet (${msg}).`); } } finally { setBusy(false); await refresh(); } }
  async function sendTestLocal() { try { const { status } = await withNotificationTimeout(Notifications.getPermissionsAsync()); if (status !== 'granted') { setStatusNote('Grant permission first.'); return; } await withNotificationTimeout(Notifications.scheduleNotificationAsync({ content: { title: 'MSpace alert', body: 'Local test notification from Promo.', sound: true }, trigger: { type: Notifications.SchedulableTriggerInputTypes.TIME_INTERVAL, seconds: 1 } })); setStatusNote('Test notification scheduled for about 1 second.'); } catch { setStatusNote('Notification test timed out. Please try again.'); } }
  return <Screen><ScrollView contentContainerStyle={screenContentStyle}>
    <Title eyebrow="Stay in the loop">Promo</Title><Subtitle>Member promotions, booking reminders, and updates, right when you need them.</Subtitle>
    <Card style={styles.statusCard}><View style={styles.statusTop}><View style={styles.iconCircle}><Ionicons name="notifications-outline" size={25} color={colors.gold} /></View><Badge tone={permission === 'granted' ? 'green' : 'muted'}>{permission === 'granted' ? 'ENABLED' : 'NOT ENABLED'}</Badge></View><Text style={styles.statusTitle}>{permission === 'granted' ? 'Notifications are on' : 'Never miss a booking reminder'}</Text><Muted>{statusNote}</Muted></Card>
    <SectionHeader>Notification access</SectionHeader><Card><Text style={styles.label}>Permission status</Text><Text style={styles.value}>{permission}</Text><Divider /><Text style={styles.label}>Expo push token</Text><Text style={styles.token} selectable>{token || 'Not registered on this device'}</Text><Muted>Booking confirmation on the Book tab also schedules a local notification. No FCM secrets are bundled in this app.</Muted><PrimaryButton label={busy ? 'Working…' : 'Enable notifications'} icon="notifications-outline" onPress={requestAndRegister} disabled={busy} /><PrimaryButton label="Send a test notification" icon="paper-plane-outline" onPress={sendTestLocal} /></Card>
  </ScrollView></Screen>;
}
const styles = StyleSheet.create({ statusCard: { backgroundColor: '#1A1813', borderColor: colors.borderStrong }, statusTop: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' }, iconCircle: { width: 48, height: 48, borderRadius: 24, backgroundColor: colors.goldSoft, justifyContent: 'center', alignItems: 'center' }, statusTitle: { color: colors.text, fontSize: 19, fontWeight: '800', marginTop: spacing.md, marginBottom: 5 }, label: { color: colors.textMuted, fontSize: 12, fontWeight: '700', marginBottom: 5 }, value: { color: colors.text, fontSize: 16, fontWeight: '700' }, token: { color: colors.textMuted, fontSize: 12, marginBottom: spacing.md, fontFamily: Platform.OS === 'android' ? 'monospace' : undefined }, });
